name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }] # Diariamente
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: alex-candido
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Fortaleza
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
