name: Metrics

on:
  schedule:
    - cron: "0 0 * * *" # todo dia à meia-noite UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: alex-candido
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Fortaleza
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          output_action: commit
          output_path: github-metrics.svg
          output_branch: main
